# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Question.create!(statement: "The view platform of the Monument was caged in after a rash of suicides in 1842", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "London Bridge was the first place in Britian it was mandatory to drive on the left.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "Tower Hill had lions and tigers until there was an attack on a member of the garrison and they were moved to the zoo in Regents Park.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "The last time Tower Hill held prisoners was the early 1950's.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "The 1908 London Olympics is where the modern marathon distance of 26 miles was set.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "The O2 dome is built on the Prime Meridian.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "Battrsea Power station is the largest brick building in Europe.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "The O2 is the largest dome in the world.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "The marathon of the 1908 London Olympics started at Windsor in order to give the Royal family a good view.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "There are 23 000 black cabs in London.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "Mark Twain was one of the inaugural passengers on the Central Line when it embarked on its maiden voyage across London in 1900.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "Aldgate Tube station is built on a plague pit containing more than 1000 bodies.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "There are more languages spoken in London than in any other city in the world.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "Big Ben is the largest clock in London.", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "One in three Londoners are foreign-born.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "London has twice as many bookshops than New York City", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "In East London you will find cash machines which offer English or Cockney for your transaction. It'll ask you to enter your Huckleberry Finn (PIN). Whether you would like your Sausage & Mash (cash) with a receipt.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "There is a pet cemetery located in Hyde Park", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "The Savoy Hotel is the only place in the UK where you are allowed to drive on the right side of the road.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "That Thames water is drinkable once the silt has settled", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "It is illegal to die in the Houses of Parliament", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "In the 17th century Oliver Cromwell brought in a law banning the eating of mince pies on Christmas Day ", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "Benjamin Franklin was a guest at Buckingham Palace for over a month due to illness. ", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "The Savoy Theatre was the first theatre, and the first public building in the world, to be lit entirely by electricity.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "In 1937 George VI became the first reigning monarch to dine in any hotel when he attended a private dinner at the Savoy.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "Judy Garland was born at the Savoy Hotel.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "The drink Bloody Mary was first made at the Savoy Hotel and named after Queen Mary I.", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "Paddington Bear was named after Paddington Station.", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "It is illegal to wear armor in the Houses of Parliament", fact_or_fiction: "t", user_id: 50000)
Question.create!(statement: "The 2012 London Olympics were awarded from the ICO meeting in Kuala Lumpar in 2007", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "George Bernard Shaw is buried in Highgate Cemetery", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "William Shakespeare performed in the opening play Henry V at the Globe Theatre", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "The first Globe Theater was destroyed by fire which was set by religious puritans who opposed theatrical performances.", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "Somerset House had to be evacuated during a party in 1658 due to a flash flood of the Thames.", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "There is a resident cat at the Bank of England which is kept for luck as it has an extra toe on each paw which is considered good-luck.", fact_or_fiction: "f", user_id: 50000)
Question.create!(statement: "The Piccadilly Line takes a detour at South Kensington to avoid a plague pit.", fact_or_fiction: "f", user_id: 50000)